### ISSUE TITLE
User Story: View Upcoming Offers

### ISSUE THREAD

**Issue by mbuturuga** [Dobbi-UDL/Dobbi-Project#15]
### Description
As a company, 
I want to see a list of upcoming offers
so that plan accordingly. 

### Requirements
- Company logged in.

### Acceptance Criteria
- The company can view a list of all their upcoming offers on a single page.
- Each offer displays its properties.
- The list is sorted by activation date, with the closest offers at the top.
- If there are too many offers, the list is paginated.

### Tasks
- [ ] Task: Implement API endpoint to fetch upcoming offers
- [ ] Task: Design Upcoming Offers UI 

### Dependencies
*These are other issues (user story level) that need to be completed before this one can be implemented.*
- [ ] User Story 1 #issue
- [ ] User Story 2 #issue

### References
- Related to #8
